version: '3.9'

services:
  web:
    build: .
    command: sh -c "python3 manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    restart: always
    image: postgres:14.1
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgresdb
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
