# Generated by Django 4.2.3 on 2023-07-13 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_profile_profile_photo_alter_log_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_photo',
            new_name='photo',
        ),
    ]
