# Generated by Django 4.2.3 on 2023-07-17 02:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logger', '0006_log_replay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='replay',
        ),
        migrations.AddField(
            model_name='log',
            name='replies',
            field=models.ManyToManyField(blank=True, related_name='reply', to='logger.log'),
        ),
        migrations.AlterField(
            model_name='log',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
