# Generated by Django 4.2.3 on 2023-07-17 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0008_remove_log_replies_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='replies',
            field=models.ManyToManyField(blank=True, related_name='reply', to='logger.log'),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
