# Generated by Django 4.2.3 on 2023-07-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0009_log_replies_delete_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='is_reply',
            field=models.BooleanField(default=False),
        ),
    ]
