# Generated by Django 4.2.3 on 2023-07-29 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0010_log_is_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='premium',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
